from selenium import webdriver
from selenium.webdriver.common.by import By
import time

driver = webdriver.Chrome()
driver.implicitly_wait(10)
driver.get('http://localhost:5173/apply')
driver.find_element(By.NAME, 'fullName').click()
driver.find_element(By.NAME, 'fullName').send_keys('Deric Joseph')
driver.find_element(By.NAME, 'email').click()
driver.find_element(By.NAME, 'email').send_keys('dericjoseph9495@gmail.com')
driver.find_element(By.NAME, 'mobile').click()
driver.find_element(By.NAME, 'mobile').send_keys('9666365589')
driver.find_element(By.NAME, 'dateOfBirth').click()
driver.find_element(By.NAME, 'dateOfBirth').send_keys('2004-06-02')
driver.find_element(By.NAME, 'gender').click()
dropdown = driver.find_element(By.NAME, 'gender')
dropdown.find_element(By.XPATH, "//option[. = 'Male']").click()
driver.find_element(By.NAME, 'address').click()
driver.find_element(By.NAME, 'address').send_keys('Kassardog')
driver.find_element(By.XPATH, "//button[contains(., 'Next Step')]").click()

driver.find_element(By.NAME, 'courseId').click()
dropdown = driver.find_element(By.NAME, 'courseId')
dropdown.find_element(By.XPATH, "//option[. = 'NEET']").click()
driver.find_element(By.NAME, 'batchId').click()
dropdown = driver.find_element(By.NAME, 'batchId')
dropdown.find_element(By.XPATH, "//option[. = 'Morning Batch']").click()
driver.find_element(By.NAME, 'tenthPercentage').click()
driver.find_element(By.NAME, 'tenthPercentage').send_keys('80')
driver.find_element(By.NAME, 'twelfthPercentage').click()
driver.find_element(By.NAME, 'twelfthPercentage').send_keys('80')
driver.find_element(By.XPATH, "//button[contains(., 'Next Step')]").click()

driver.find_element(By.NAME, 'parentName').click()
driver.find_element(By.NAME, 'parentName').send_keys('Joseph')
driver.find_element(By.NAME, 'relationship').click()
dropdown = driver.find_element(By.NAME, 'relationship')
dropdown.find_element(By.XPATH, "//option[. = 'Father']").click()
driver.find_element(By.NAME, 'parentEmail').click()
driver.find_element(By.NAME, 'parentEmail').send_keys('joseph@gmail.com')
driver.find_element(By.NAME, 'parentMobile').click()
driver.find_element(By.NAME, 'parentMobile').send_keys('9855632512')
driver.find_element(By.XPATH, "//button[contains(., 'Next Step')]").click()

driver.find_element(By.NAME, 'tenthCertificate').send_keys(r'D:\Edusphere1\Testing\dummy.pdf')
driver.find_element(By.NAME, 'twelfthCertificate').send_keys(r'D:\Edusphere1\Testing\dummy.pdf')
driver.find_element(By.XPATH, "//button[contains(., 'Submit Admission Application')]").click()
time.sleep(3)
try:
    print('Current step HTML:', driver.find_element(By.TAG_NAME, 'form').get_attribute('innerHTML'))
except:
    print('Current page HTML:', driver.find_element(By.TAG_NAME, 'body').get_attribute('innerHTML'))
print('Validation errors?', driver.execute_script('return Array.from(document.querySelectorAll("p.text-red-500")).map(e => e.innerText)'))
driver.quit()
