# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestQuizmanagement():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.implicitly_wait(10)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_quizmanagement(self):
    self.driver.get("http://localhost:5173/login")
    self.driver.set_window_size(1552, 880)
    self.driver.find_element(By.NAME, "email").send_keys("alen.chemistry@edusphere.com")
    self.driver.find_element(By.NAME, "password").send_keys("Edu@123", Keys.RETURN)
    WebDriverWait(self.driver, 10).until(
        expected_conditions.url_contains("/teacher")
    )
    self.driver.get("http://localhost:5173/teacher/quizzes")
    WebDriverWait(self.driver, 10).until(
        expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".to-purple-600"))
    )
    self.driver.find_element(By.CSS_SELECTOR, ".to-purple-600").click()
    WebDriverWait(self.driver, 10).until(
        expected_conditions.presence_of_element_located((By.NAME, "title"))
    )
    self.driver.find_element(By.NAME, "title").click()
    self.driver.find_element(By.NAME, "title").send_keys("chemistry 3")
    from selenium.webdriver.support.ui import Select
    Select(self.driver.find_element(By.NAME, "batch")).select_by_visible_text("JEE Evening Batch")
    Select(self.driver.find_element(By.NAME, "subject")).select_by_index(1)
    self.driver.execute_script("let el = document.getElementsByName('startDate')[0]; let tracker = el._valueTracker; if (tracker) tracker.setValue(el.value); el.value = '2026-10-01'; el.dispatchEvent(new Event('input', {bubbles: true})); el.dispatchEvent(new Event('change', {bubbles: true}));")
    self.driver.find_element(By.CSS_SELECTOR, ".grid:nth-child(5) .border:nth-child(1)").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".grid:nth-child(5) .border:nth-child(1)")
    dropdown.find_element(By.XPATH, "//option[. = '09']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".grid:nth-child(5) .border:nth-child(3)").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".grid:nth-child(5) .border:nth-child(3)")
    dropdown.find_element(By.XPATH, "//option[. = '59']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".grid:nth-child(5) .border:nth-child(4)").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".grid:nth-child(5) .border:nth-child(4)")
    dropdown.find_element(By.XPATH, "//option[. = 'AM']").click()
    self.driver.execute_script("let el = document.getElementsByName('endDate')[0]; let tracker = el._valueTracker; if (tracker) tracker.setValue(el.value); el.value = '2026-10-01'; el.dispatchEvent(new Event('input', {bubbles: true})); el.dispatchEvent(new Event('change', {bubbles: true}));")
    self.driver.find_element(By.CSS_SELECTOR, ".grid:nth-child(6) .border:nth-child(1)").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".grid:nth-child(6) .border:nth-child(1)")
    dropdown.find_element(By.XPATH, "//option[. = '10']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".grid:nth-child(6) .border:nth-child(3)").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".grid:nth-child(6) .border:nth-child(3)")
    dropdown.find_element(By.XPATH, "//option[. = '05']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".grid:nth-child(6) .border:nth-child(4)").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".grid:nth-child(6) .border:nth-child(4)")
    dropdown.find_element(By.XPATH, "//option[. = 'AM']").click()
    self.driver.find_element(By.NAME, "negativeMarkingEnabled").click()
    self.driver.find_element(By.NAME, "defaultNegativeMark").clear()
    self.driver.find_element(By.NAME, "defaultNegativeMark").send_keys("4")
    self.driver.execute_script("document.querySelectorAll('input, select, textarea').forEach(el => el.removeAttribute('required'));")
    submit_btn = self.driver.find_element(By.XPATH, "//button[contains(., 'Save & Continue')]")
    self.driver.execute_script("arguments[0].click();", submit_btn)
    try:
        WebDriverWait(self.driver, 5).until(
            expected_conditions.url_contains("/edit")
        )
    except:
        try:
            print("ALERT: " + self.driver.switch_to.alert.text)
            self.driver.switch_to.alert.accept()
        except:
            print("No alert, URL didn't change.")
    WebDriverWait(self.driver, 10).until(
        expected_conditions.element_to_be_clickable((By.XPATH, "//button[contains(., 'Add Question')]"))
    )
    self.driver.find_element(By.XPATH, "//button[contains(., 'Add Question')]").click()
    WebDriverWait(self.driver, 10).until(
        expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "textarea.p-3"))
    )
    self.driver.find_element(By.CSS_SELECTOR, ".p-3").click()
    self.driver.find_element(By.CSS_SELECTOR, ".p-3").send_keys("who is midhun suresh")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-emerald-50").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-emerald-50").send_keys("ayyyoo")
    self.driver.find_element(By.CSS_SELECTOR, ".gap-2:nth-child(2) > .flex-1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".gap-2:nth-child(2) > .flex-1").send_keys("vanam")
    self.driver.find_element(By.CSS_SELECTOR, ".grid > .flex:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".flex:nth-child(2) > .w-4").click()
    self.driver.find_element(By.CSS_SELECTOR, ".gap-2:nth-child(3) > .flex-1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".gap-2:nth-child(3) > .flex-1").send_keys("idukki")
    self.driver.find_element(By.CSS_SELECTOR, ".gap-2:nth-child(4) > .flex-1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".gap-2:nth-child(4) > .flex-1").send_keys("uio")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-emerald-50").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-emerald-50").send_keys("hj")
    self.driver.find_element(By.XPATH, "//button[contains(., 'Add Question')]").click()
    WebDriverWait(self.driver, 10).until(
        expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".bg-white:nth-child(3) .w-full"))
    )
    self.driver.find_element(By.CSS_SELECTOR, ".bg-white:nth-child(3) .w-full").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-white:nth-child(3) .w-full").send_keys("who is abin")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-white:nth-child(3) .flex:nth-child(3) > .flex-1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-white:nth-child(3) .flex:nth-child(3) > .flex-1").send_keys("palapra")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-white:nth-child(3) .flex:nth-child(3) > .w-4").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-white:nth-child(3) .flex:nth-child(1) > .flex-1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-white:nth-child(3) .flex:nth-child(1) > .flex-1").send_keys("fg")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-white:nth-child(3) .flex:nth-child(2) > .flex-1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-white:nth-child(3) .flex:nth-child(2) > .flex-1").send_keys("hj")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-white:nth-child(3) .flex:nth-child(4) > .flex-1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bg-white:nth-child(3) .flex:nth-child(4) > .flex-1").send_keys("gh")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-emerald-600 > span").click()
    assert self.driver.switch_to.alert.text == "Are you sure you want to publish this quiz? It cannot be edited afterward."
    self.driver.switch_to.alert.accept()
  
