# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLoginn():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginn(self):
    self.driver.get("http://localhost:5173/login")
    self.driver.set_window_size(944, 533)
    self.driver.find_element(By.NAME, "email").send_keys("telecareplus@gmail.com")
    self.driver.find_element(By.NAME, "password").send_keys("123456")
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("alen.chemistry@edusphere.com")
    self.driver.find_element(By.NAME, "password").send_keys("Edu@123")
    self.driver.find_element(By.CSS_SELECTOR, ".right-3\\.5").click()
    self.driver.find_element(By.CSS_SELECTOR, ".right-3\\.5").click()
    self.driver.find_element(By.CSS_SELECTOR, ".focus\\3Aring-offset-2").click()
  
