# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestForgotpassword():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_forgotpassword(self):
    self.driver.get("http://localhost:5173/forgot-password")
    self.driver.set_window_size(1552, 880)
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("melbinsabu600@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".justify-center > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".lg\\3Aw-5\\/12").click()
    self.driver.find_element(By.NAME, "tempPassword").click()
    self.driver.find_element(By.NAME, "tempPassword").send_keys("Reset@61468")
    self.driver.find_element(By.NAME, "newPassword").click()
    self.driver.find_element(By.NAME, "newPassword").send_keys("123456")
    self.driver.find_element(By.NAME, "confirmPassword").click()
    self.driver.find_element(By.NAME, "confirmPassword").send_keys("123456")
    self.driver.find_element(By.CSS_SELECTOR, ".justify-center > span").click()
    assert self.driver.switch_to.alert.text == "Password updated successfully! Welcome to EduSphere."
  
