# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRegistration():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.implicitly_wait(10)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_registration(self):
    self.driver.get("http://localhost:5173/apply")
    self.driver.set_window_size(1552, 880)
    self.driver.find_element(By.NAME, "fullName").click()
    self.driver.find_element(By.NAME, "fullName").send_keys("Deric Joseph")
    self.driver.find_element(By.NAME, "email").click()
    unique_email = f"dericjoseph{int(time.time())}@gmail.com"
    self.driver.find_element(By.NAME, "email").send_keys(unique_email)
    self.driver.find_element(By.NAME, "mobile").click()
    unique_mobile = "9" + str(int(time.time() * 1000) % 1000000000).zfill(9)
    self.driver.find_element(By.NAME, "mobile").send_keys(unique_mobile)
    self.driver.find_element(By.NAME, "dateOfBirth").click()
    self.driver.find_element(By.NAME, "dateOfBirth").send_keys("02-06-2004")
    self.driver.find_element(By.NAME, "gender").click()
    dropdown = self.driver.find_element(By.NAME, "gender")
    dropdown.find_element(By.XPATH, "//option[. = 'Male']").click()
    self.driver.find_element(By.NAME, "address").click()
    self.driver.find_element(By.NAME, "address").send_keys("Kassardog")
    self.driver.find_element(By.CSS_SELECTOR, ".px-6").click()
    self.driver.find_element(By.NAME, "courseId").click()
    dropdown = self.driver.find_element(By.NAME, "courseId")
    dropdown.find_element(By.XPATH, "//option[. = 'NEET']").click()
    self.driver.find_element(By.NAME, "batchId").click()
    dropdown = self.driver.find_element(By.NAME, "batchId")
    dropdown.find_element(By.XPATH, "//option[. = 'Morning Batch']").click()
    self.driver.find_element(By.NAME, "tenthPercentage").click()
    self.driver.find_element(By.NAME, "tenthPercentage").send_keys("80")
    self.driver.find_element(By.NAME, "twelfthPercentage").click()
    self.driver.find_element(By.NAME, "twelfthPercentage").send_keys("80")
    self.driver.find_element(By.CSS_SELECTOR, ".px-6").click()
    self.driver.find_element(By.NAME, "parentName").click()
    self.driver.find_element(By.NAME, "parentName").send_keys("Joseph")
    self.driver.find_element(By.NAME, "relationship").click()
    dropdown = self.driver.find_element(By.NAME, "relationship")
    dropdown.find_element(By.XPATH, "//option[. = 'Father']").click()
    self.driver.find_element(By.NAME, "parentEmail").click()
    self.driver.find_element(By.NAME, "parentEmail").send_keys("joseph@gmail.com")
    self.driver.find_element(By.NAME, "parentMobile").click()
    self.driver.find_element(By.NAME, "parentMobile").send_keys("9855632512")
    self.driver.find_element(By.CSS_SELECTOR, ".px-6").click()
    self.driver.find_element(By.NAME, "tenthCertificate").send_keys(r"D:\Edusphere1\Testing\dummy.pdf")
    self.driver.find_element(By.NAME, "twelfthCertificate").send_keys(r"D:\Edusphere1\Testing\dummy.pdf")
    self.driver.find_element(By.CSS_SELECTOR, ".focus\\3Aoutline-none").click()
    self.driver.find_element(By.LINK_TEXT, "Go to Login Page →").click()
    self.driver.find_element(By.NAME, "email").send_keys("alen.chemistry@edusphere.com")
    self.driver.find_element(By.NAME, "password").send_keys("Edu@123")
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("dericjoseph")
  
