# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTimetable():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_timetable(self):
    self.driver.get("http://localhost:5173/login")
    self.driver.set_window_size(1552, 880)
    time.sleep(1)
    self.driver.find_element(By.NAME, "email").send_keys("melbin@gmail.com")
    self.driver.find_element(By.NAME, "password").send_keys("123456", Keys.RETURN)
    WebDriverWait(self.driver, 10).until(
        expected_conditions.url_contains("/administrator")
    )
    self.driver.get("http://localhost:5173/administrator/timetable")
    WebDriverWait(self.driver, 10).until(
        expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".border-amber-500"))
    )
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, ".border-amber-500").click()
    self.driver.find_element(By.CSS_SELECTOR, ".inline-flex").click()
    self.driver.find_element(By.CSS_SELECTOR, ".p-3").click()
    self.driver.find_element(By.CSS_SELECTOR, ".p-3").send_keys("english")
    self.driver.find_element(By.CSS_SELECTOR, ".inline-flex > span").click()
  
