# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestChangepassword():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_changepassword(self):
    # 1. Login
    self.driver.get("http://localhost:5173/login")
    self.driver.set_window_size(1500, 1000)
    WebDriverWait(self.driver, 10).until(
        expected_conditions.presence_of_element_located((By.NAME, "email"))
    )
    self.driver.find_element(By.NAME, "email").send_keys("divinbabu2027@mca.ajce.in")
    self.driver.find_element(By.NAME, "password").send_keys("123456", Keys.RETURN)
    
    # 2. Wait for redirect (we will wait until URL contains 'student')
    WebDriverWait(self.driver, 10).until(
        expected_conditions.url_contains("/student")
    )
    
    # 3. Go to change password explicitly
    self.driver.get("http://localhost:5173/change-password")
    
    # 4. Fill form
    WebDriverWait(self.driver, 10).until(
        expected_conditions.presence_of_element_located((By.NAME, "currentPassword"))
    )
    self.driver.find_element(By.NAME, "currentPassword").send_keys("123456")
    self.driver.find_element(By.NAME, "newPassword").send_keys("123456")
    self.driver.find_element(By.NAME, "confirmPassword").send_keys("123456")
    
    # 5. Submit
    submit_btn = self.driver.find_element(By.XPATH, "//button[@type='submit']")
    submit_btn.click()
    
    # Wait to make sure alert or redirect happens
    time.sleep(2)
