# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestForgot():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_forgot(self):
    self.driver.get("http://localhost:5173/login")
    self.driver.set_window_size(1552, 880)
    
    # Perform login
    WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.NAME, "email")))
    self.driver.find_element(By.NAME, "email").send_keys("alen.chemistry@edusphere.com")
    self.driver.find_element(By.NAME, "password").send_keys("Edu@123")
    self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
    
    # Wait until redirected to dashboard
    WebDriverWait(self.driver, 10).until(expected_conditions.url_contains("/dashboard"))

    # Now go to create quiz page
    self.driver.get("http://localhost:5173/teacher/quizzes/create")
    
    # Wait for the quiz form to load
    WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.NAME, "title")))
    
    # Make sure we use a unique title each time just in case
    unique_title = f"Tom {int(time.time())}"
    self.driver.find_element(By.NAME, "title").click()
    self.driver.find_element(By.NAME, "title").send_keys(unique_title)
    
    # Using send_keys on selects ensures React onChange fires
    self.driver.find_element(By.NAME, "batch").send_keys("JEE Evening Batch")
    self.driver.find_element(By.NAME, "subject").send_keys("Chemistry")
    
    # Using JS native setter for date inputs to ensure it works across locales
    self.driver.execute_script('''
        var input = arguments[0];
        var nativeInputValueSetter = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, 'value').set;
        nativeInputValueSetter.call(input, '2026-10-07');
        var ev = new Event('input', { bubbles: true});
        input.dispatchEvent(ev);
    ''', self.driver.find_element(By.NAME, "startDate"))

    self.driver.find_element(By.CSS_SELECTOR, ".grid:nth-child(5) .border:nth-child(3)").send_keys("15")
    
    self.driver.execute_script('''
        var input = arguments[0];
        var nativeInputValueSetter = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, 'value').set;
        nativeInputValueSetter.call(input, '2026-10-07');
        var ev = new Event('input', { bubbles: true});
        input.dispatchEvent(ev);
    ''', self.driver.find_element(By.NAME, "endDate"))
    
    self.driver.find_element(By.CSS_SELECTOR, ".grid:nth-child(6) .border:nth-child(3)").send_keys("20")
    
    # Click 'Save & Continue' to submit the quiz settings
    self.driver.find_element(By.XPATH, "//button[@type='submit']").click()
    
    # Wait for the URL to contain '/edit' indicating navigation was successful
    try:
        WebDriverWait(self.driver, 5).until(expected_conditions.url_contains("/edit"))
    except Exception as e:
        try:
            alert = self.driver.switch_to.alert
            error_text = alert.text
            alert.accept()
            raise Exception(f"Form submission failed with alert: {error_text}")
        except:
            raise e
    
    # Wait for the 'Add Question' button to appear
    WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.XPATH, "//button[contains(., 'Add Question')]")))
    time.sleep(1) # Extra stability wait
    self.driver.find_element(By.XPATH, "//button[contains(., 'Add Question')]").click()
    
    # Wait for the question textarea to be visible
    WebDriverWait(self.driver, 10).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, "textarea.p-3")))
    self.driver.find_element(By.CSS_SELECTOR, ".p-3").click()
    self.driver.find_element(By.CSS_SELECTOR, ".p-3").send_keys("who is a person")
    
    # Avoid brittle nth-child selectors which change dynamically based on state
    # First option
    self.driver.find_element(By.CSS_SELECTOR, ".gap-2:nth-child(1) > .flex-1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".gap-2:nth-child(1) > .flex-1").send_keys("ghj")
    
    self.driver.find_element(By.CSS_SELECTOR, ".gap-2:nth-child(2) > .flex-1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".gap-2:nth-child(2) > .flex-1").send_keys("dfghj")
    
    self.driver.find_element(By.CSS_SELECTOR, ".gap-2:nth-child(3) > .flex-1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".gap-2:nth-child(3) > .flex-1").send_keys("dfghjk")
    
    self.driver.find_element(By.CSS_SELECTOR, ".gap-2:nth-child(4) > .flex-1").click()
    self.driver.find_element(By.CSS_SELECTOR, ".gap-2:nth-child(4) > .flex-1").send_keys("dfghjk")
    
    # Select first option as correct answer
    self.driver.find_element(By.CSS_SELECTOR, ".gap-2:nth-child(1) > .w-4").click()
    
    # Questions auto-save on blur, so we can just click Publish
    # Click publish (button with emerald-600 background or text 'Publish')
    self.driver.find_element(By.XPATH, "//button[contains(., 'Publish')]").click()
    
    # Wait for the confirmation alert
    WebDriverWait(self.driver, 10).until(expected_conditions.alert_is_present())
    assert self.driver.switch_to.alert.text == "Are you sure you want to publish this quiz? It cannot be edited afterward."
    self.driver.switch_to.alert.accept()
    
    # Wait for navigation back to quizzes list to complete the test gracefully
    time.sleep(2)
